data_loader:
  name: "T_Less"
  input_size: 224
  config:
    dataset_path: "datasets/t-less_v2"
    dirs: ["train_kinect/01", "train_kinect/02", "train_kinect/03",
           "train_kinect/04", "train_kinect/05", "train_kinect/06",
           "train_kinect/07", "train_kinect/08", "train_kinect/09",
           "train_kinect/10", "train_kinect/11", "train_kinect/12",
           "train_kinect/13", "train_kinect/14", "train_kinect/15",
           "train_kinect/16", "train_kinect/17", "train_kinect/18",
           "train_kinect/19", "train_kinect/20", "train_kinect/21",
           "train_kinect/22", "train_kinect/23", "train_kinect/24",
           "train_kinect/25", "train_kinect/26", "train_kinect/27",
           "train_kinect/28", "train_kinect/29", "train_kinect/30"]
    hdf5: "tless.hdf5"
    biterion: True
    blur: False
train:
  loss_function: "cosine"
  device: "cuda:1"
  num_outputs: 6
  num_epochs: 50
  num_channels: 3
  batch_size: 32
  learning_rate: 0.0001
  model: "resnet18"
  save_as: "tless_multimodal/cosine"
  save_dir: "models/tless_multimodal/cosine"
  resume: False
