data_loader:
  name: "UPNAHeadPose"
  input_size: 224
  config:
    dataset_path: "datasets/upna"
    preprocess_path: "datasets/ryp_upna"
    biterion: False
    euler_noise: 0 
    quat_noise: [-150, -100, -75, 0]
train:
  loss_function: "bingham"
  loss_parameters:
    lookup_table_file: "precomputed/lookup_-500_0_40.dill"
  device: "cuda"
  num_outputs: 19
  num_epochs: 20
  num_channels: 3
  batch_size: 32
  learning_rate: 0.00005
  model: "resnet18"
  save_as: "calibration/upna/150_100_75"
  save_dir: "models/calibration/upna/150_100_75"
  resume: False 
