data_loader:
  name: "IDIAP"
  input_size: 224
  config:
    dataset_path: "datasets/IDIAPHeadPose"
    preprocess_path: "datasets/IDIAPHeadPose"
    euler_noise: 0
    quat_noise:
    biterion: False
train:
  loss_function: "mse"
  device: "cuda"
  num_outputs: 4
  num_epochs: 10 
  num_channels: 3
  batch_size: 32
  learning_rate: 0.0001
  model: "resnet18"
  save_as: "baselines/idiap/mse"
  save_dir: "models/baselines/idiap/mse"
  resume: False 
