data_loader:
  name: "UPNAHeadPose"
  input_size: 224
  config:
    dataset_path: "datasets/upna"
    preprocess_path: "datasets/ryp_upna"
    biterion: True
    euler_noise: 0 
    quat_noise: 
train:
  loss_function: "cosine"
  device: "cuda"
  num_outputs: 6 
  num_epochs: 10 
  num_channels: 3
  batch_size: 32
  learning_rate: 0.0001
  model: "resnet18"
  save_as: "baselines/upna/cosine"
  save_dir: "models/baselines/upna/cosine"
  resume: False 
